#!/bin/bash

outFile="results-1.txt"
rm -f $outFile

echo -e 'Number of elements' >> $outFile
echo -e '\t8\t16\t32\t64\t128\t256\t512' >> $outFile
for i in 1024 2048 4096 8192 16384 32768 65536 131072 262144 524288 1048576 2097152 4194304 8388608
do 
    echo -e -n $i'\t' >> $outFile
    for t in 8 16 32 64 128 256 512
    do 
        g++ -DNMB=$i -DLOCAL_SIZE=$t first.cpp -o first ./CL/libOpenCL.so -lm -fopenmp
        ./first
    done
    echo '' >> $outFile
done