#!/bin/bash

# number of threads:
for t in 1 2 4 6 8
do
    echo NUMT = $t
    # number of trials
    for s in 10 100 1000 10000 100000
    do
        g++ -DNUMT=$t -DNUMTRIALS=$s proj.cpp -o proj -lm -fopenmp
        ./proj
    done
done
