#!/bin/bash

outFile="results.txt"
rm -f $outFile

echo -e '\t16\t32\t64' >> $outFile
for trials in 16384 32768 65536 131072 262144 524288
do
    echo -e -n $trials'\t' >> $outFile
    for block in 16 32 64
    do
        rm -f ./monteCarlo
        make NUMTRIALS=$trials BLOCKSIZE=$block
        ./monteCarlo
    done
    echo -e -n '\n' >> $outFile
done